# Generated by Django 4.0.3 on 2022-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_food_desc_alter_team_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='d_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
