# Generated by Django 4.0.3 on 2022-04-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
