# Generated by Django 4.0.3 on 2022-04-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
