# Generated by Django 4.0.3 on 2022-05-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_food_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
