# Generated by Django 4.0.3 on 2022-05-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_remove_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='d_price',
            field=models.IntegerField(default=0),
        ),
    ]
