# Generated by Django 4.0.3 on 2023-05-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_orderline_remove_order_food_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
