# Generated by Django 4.0.3 on 2023-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_remove_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
