# Generated by Django 4.0.3 on 2023-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_orderline_name_orderline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='image',
            field=models.ImageField(default=0, upload_to='food_images'),
            preserve_default=False,
        ),
    ]
