# Generated by Django 4.0.3 on 2023-05-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_orderline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commune',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
