# Generated by Django 4.0.3 on 2023-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_order_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='orderid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
