# Generated by Django 4.0.3 on 2023-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_orderline_orderid_orderline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
