# Generated by Django 4.0.3 on 2023-05-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_alter_orderline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='canvas_images')),
            ],
        ),
    ]
