# Generated by Django 4.0.3 on 2023-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0022_canvasimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasimage',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
